"""
models.py — Data-access functions.  All SQL lives here; route handlers never
            write queries directly.
"""
from database import get_connection, query


def get_customer_by_username(username: str, db_path=None):
    """
    Return the full customer record for *username*, or None if not found.
    The record is a sqlite3.Row and supports both dict and index access.
    """
    return query(
        "SELECT * FROM customers WHERE username = ?",
        (username,),
        db_path=db_path,
        fetchone=True,
    )


def get_balance(customer_id: int, db_path=None) -> float:
    """Return the current balance for the given *customer_id*."""
    row = query(
        "SELECT balance FROM customers WHERE id = ?",
        (customer_id,),
        db_path=db_path,
        fetchone=True,
    )
    return float(row["balance"]) if row else 0.0


def update_balance(customer_id: int, new_balance: float, db_path=None) -> None:
    """Overwrite the balance for the given *customer_id* with *new_balance*."""
    query(
        "UPDATE customers SET balance = ? WHERE id = ?",
        (new_balance, customer_id),
        db_path=db_path,
    )


def withdraw_atomic(customer_id: int, amount: float, db_path=None) -> bool:
    """
    Atomically deduct *amount* from the customer's balance in a single SQL
    statement, guarded by a ``balance >= amount`` predicate.

    Returns True if the withdrawal succeeded (rowcount == 1), or False if
    the balance was insufficient at the moment the write was applied.

    This eliminates the TOCTOU race that exists when a separate SELECT is
    followed by a separate UPDATE — two concurrent requests can both pass a
    Python-level balance check, then both commit, producing a negative balance.
    Using a single conditional UPDATE the database enforces the constraint
    atomically under its own write lock.
    """
    from database import DB_PATH
    import sqlite3

    path = db_path if db_path is not None else DB_PATH
    conn = sqlite3.connect(path)
    conn.row_factory = sqlite3.Row
    try:
        cursor = conn.cursor()
        cursor.execute(
            "UPDATE customers SET balance = balance - ? "
            "WHERE id = ? AND balance >= ?",
            (amount, customer_id, amount),
        )
        conn.commit()
        return cursor.rowcount == 1
    finally:
        conn.close()


def log_transaction(
    customer_id: int,
    transaction_type: str,
    amount: float,
    db_path=None,
) -> None:
    """
    Insert a row into the transactions table.

    *transaction_type* must be either ``"deposit"`` or ``"withdrawal"``.
    The timestamp is generated by SQLite's CURRENT_TIMESTAMP.
    """
    query(
        "INSERT INTO transactions (customer_id, transaction_type, amount) VALUES (?, ?, ?)",
        (customer_id, transaction_type, amount),
        db_path=db_path,
    )
