"""
models.py — Data-access functions.  All SQL lives here; route handlers never
            write queries directly.
"""
from database import query


def get_customer_by_username(username: str, db_path=None):
    """
    Return the full customer record for *username*, or None if not found.
    The record is a sqlite3.Row and supports both dict and index access.
    """
    return query(
        "SELECT * FROM customers WHERE username = ?",
        (username,),
        db_path=db_path,
        fetchone=True,
    )


def get_balance(customer_id: int, db_path=None) -> float:
    """Return the current balance for the given *customer_id*."""
    row = query(
        "SELECT balance FROM customers WHERE id = ?",
        (customer_id,),
        db_path=db_path,
        fetchone=True,
    )
    return float(row["balance"]) if row else 0.0


def update_balance(customer_id: int, new_balance: float, db_path=None) -> None:
    """Overwrite the balance for the given *customer_id* with *new_balance*."""
    query(
        "UPDATE customers SET balance = ? WHERE id = ?",
        (new_balance, customer_id),
        db_path=db_path,
    )


def log_transaction(
    customer_id: int,
    transaction_type: str,
    amount: float,
    db_path=None,
) -> None:
    """
    Insert a row into the transactions table.

    *transaction_type* must be either ``"deposit"`` or ``"withdrawal"``.
    The timestamp is generated by SQLite's CURRENT_TIMESTAMP.
    """
    query(
        "INSERT INTO transactions (customer_id, transaction_type, amount) VALUES (?, ?, ?)",
        (customer_id, transaction_type, amount),
        db_path=db_path,
    )
